### ISSUE TITLE
Support for multiple RGB instances

### ISSUE THREAD

**Issue by shanevanj** [joushx/Arduino-RGB-Tools#7]
I could not get multiple instances to work and modified the library to achieve this. I don't know how to create a branch etc in github - how do I send you my changes etc ?

**Comment by joushx** [comment]
Create a fork with the "Fork" button and make your changes in this repository. When your code is ready, create a pull request which I'll be able to merge into the main code.

**Comment by joushx** [comment]
You may want to make a reference to this issue by including `#7` in the title of your pull request. :)
